[project]
name = "flax-weightwatcher"
version = "0.1.1"
description = "A smaller, faster, cleaner WeightWatcher for FLAX/JAX with XLA"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flax",
    "jax",
    "jaxtyping",
    "numpy",
    "pandas",
    "powerlaw>=1.5",
]
